### ISSUE TITLE
OpenSSL commands invalid

### ISSUE THREAD

**Issue by vinsec** [makerdiary/nrf52-u2f#4]
https://github.com/makerdiary/nrf52-u2f/blob/b0cd9f616e3b2230838b0db378a93fa625c4ab5f/tools/generate-certs.sh#L44

I installed the openssl by ubuntu apt command.The OpenSSL version in my Ubuntu 18.04 is 1.1.0g.
There is no such command that named "list-standard-command" in the current version.So the shell script need to be modified.I would be glad to launch a pull request or you could do it by yourself.

**Comment by caizelin** [comment]
@vinsec Pull requests are always welcome. Thanks for your commits.

**Comment by vinsec** [comment]
```
C:\Users\>nrfutil.exe dfu usb-serial -pkg nrf52_u2f_bootloader_v1.0.0_mdk_dongle.zip -p COM4

Traceback (most recent call last):
  File "nordicsemi\__main__.py", line 1457, in <module>
  File "click\core.py", line 764, in __call__
  File "click\core.py", line 717, in main
  File "click\core.py", line 1137, in invoke
  File "click\core.py", line 1137, in invoke
  File "click\core.py", line 956, in invoke
  File "click\core.py", line 555, in invoke
  File "nordicsemi\__main__.py", line 999, in usb_serial
  File "nordicsemi\__main__.py", line 954, in do_serial
  File "nordicsemi\dfu\dfu.py", line 125, in dfu_send_images
  File "nordicsemi\dfu\dfu.py", line 97, in _dfu_send_image
  File "nordicsemi\dfu\dfu_transport_serial.py", line 256, in send_init_packet
  File "nordicsemi\dfu\dfu_transport_serial.py", line 422, in __execute
  File "nordicsemi\dfu\dfu_transport_serial.py", line 503, in __get_response
pc_ble_driver_py.exceptions.NordicSemiException: Extended Error 0x05: The firmware version is too low. For an application, the version must be greate
r than or equal to the current application. For a bootloader, it must be greater than the current version. This requirement prevents downgrade attack
s.
[22172] Failed to execute script __main__
```
----
When tried to flush the bootloader into my usb dongle and the error occurred.
Is the factory version of the bootloader higher than the [precompiled version](https://wiki.makerdiary.com/nrf52-u2f/upgrading/#get-the-latest-pre-built-firmware) ?
The mdk_usb_dongle is bought from Tmall makediary.

**Comment by caizelin** [comment]
@vinsec You are right. The bootloader version of your dongle is up to date. It is `v1.2.0` which will be released soon.

**Comment by snowyu** [comment]
@caizelin is not the source of repo the newest code? I just buy one pls fix it asap
